import java.io.File;
import java.io.IOException;
import javax.swing.*;
import java.lang.Object;
import java.util.*;

/*
 * pApp.java
 *
 * Created on May 28, 2007, 6:03 PM
 */

/**
 *
 * @author  meg pirrung
 */
public class JAR3DMoleculeAlignerWindowed extends javax.swing.JFrame {


	//my vars
	String fasta;
	String statusLabeltxt = "";
	int model;
	Vector alignment;
	Vector models;
	Vector sequences;

	/** Creates new form pApp */
	public JAR3DMoleculeAlignerWindowed() {
		alignment = new Vector();

		getFiles();

		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {
        alignmentPanel = new javax.swing.JPanel();
        alignmentPane = new javax.swing.JScrollPane();
        alignmentList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        modelPanel = new javax.swing.JPanel();
        modelMenu = new javax.swing.JComboBox();
        seqPanel = new javax.swing.JPanel();
        seqMenu = new javax.swing.JComboBox();
        alignButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        statusLabel = new javax.swing.JTextField();
        numSeqPanel = new javax.swing.JPanel();
        numSeqField = new javax.swing.JTextField();
        limitPanel = new javax.swing.JPanel();
        limitField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        statusIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parser Applet");
        alignmentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Alignment"));
        alignmentList.setFont(new java.awt.Font("Lucida Console", 0, 11));
        alignmentList.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return alignment.size(); }
            public Object getElementAt(int i) { return alignment.get(i); }
        });
        alignmentPane.setViewportView(alignmentList);

        jLabel3.setText("5'");

        jLabel4.setText("3'");

        javax.swing.GroupLayout alignmentPanelLayout = new javax.swing.GroupLayout(alignmentPanel);
        alignmentPanel.setLayout(alignmentPanelLayout);
        alignmentPanelLayout.setHorizontalGroup(
            alignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignmentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(alignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alignmentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                    .addGroup(alignmentPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1210, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        alignmentPanelLayout.setVerticalGroup(
            alignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alignmentPanelLayout.createSequentialGroup()
                .addGroup(alignmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alignmentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        modelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Model Type"));
        modelMenu.setModel(new javax.swing.DefaultComboBoxModel() {
            
			public int getSize() { return models.size(); }
            
			public Object getElementAt(int i) { return models.get(i); }
        });

        javax.swing.GroupLayout modelPanelLayout = new javax.swing.GroupLayout(modelPanel);
        modelPanel.setLayout(modelPanelLayout);
        modelPanelLayout.setHorizontalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelPanelLayout.createSequentialGroup()
                .addComponent(modelMenu, 0, 430, Short.MAX_VALUE)
                .addContainerGap())
        );
        modelPanelLayout.setVerticalGroup(
            modelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(modelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        seqPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fasta File"));
        seqMenu.setModel(new javax.swing.DefaultComboBoxModel() {
            
			public int getSize() { return sequences.size(); }
            
			public Object getElementAt(int i) { return sequences.get(i); }
        });

        javax.swing.GroupLayout seqPanelLayout = new javax.swing.GroupLayout(seqPanel);
        seqPanel.setLayout(seqPanelLayout);
        seqPanelLayout.setHorizontalGroup(
            seqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seqMenu, 0, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        seqPanelLayout.setVerticalGroup(
            seqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seqMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        alignButton.setText("Align");
        alignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alignButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.JLabel() {
            
			public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("http://i11.tinypic.com/6by37dz.gif")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());

        jProgressBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        statusLabel.setEditable(false);
        statusLabel.setText(statusLabeltxt);

        numSeqPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Number of Sequences"));
        numSeqField.setText("10");
        numSeqField.addKeyListener(new java.awt.event.KeyAdapter() {
            
			public void keyTyped(java.awt.event.KeyEvent evt) {
                myKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout numSeqPanelLayout = new javax.swing.GroupLayout(numSeqPanel);
        numSeqPanel.setLayout(numSeqPanelLayout);
        numSeqPanelLayout.setHorizontalGroup(
            numSeqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numSeqPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numSeqField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );
        numSeqPanelLayout.setVerticalGroup(
            numSeqPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(numSeqField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        limitPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Limits"));
        limitField.setText("20");
        limitField.addKeyListener(new java.awt.event.KeyAdapter() {
            
			public void keyTyped(java.awt.event.KeyEvent evt) {
               myKeyTyped(evt);
            }
        });

        jLabel2.setText("\u00b1");

        javax.swing.GroupLayout limitPanelLayout = new javax.swing.GroupLayout(limitPanel);
        limitPanel.setLayout(limitPanelLayout);
        limitPanelLayout.setHorizontalGroup(
            limitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(limitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
        );
        limitPanelLayout.setVerticalGroup(
            limitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(limitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(limitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        statusIcon.setIcon(new javax.swing.JLabel() {
            
			public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("http://i7.tinypic.com/5y00but.gif")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numSeqPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limitPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(statusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addComponent(alignmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alignButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(limitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numSeqPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seqPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alignmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }

	private void alignButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
        loadAlignment();
        }
        catch (IOException e) {
            statusLabeltxt = "Could not open alignment";
            System.out.println("Could not open alignment");
            System.out.println(e);
        }
    //    initComponents();
    }      

	private void myKeyTyped(java.awt.event.KeyEvent evt) {
		int k=evt.getKeyChar();
		if(k>47 && k<58)
		{
		}
		else
		{
			evt.setKeyChar((char)java.awt.event.KeyEvent.VK_CLEAR);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	 public static void main(String args[]) {
		 java.awt.EventQueue.invokeLater(new Runnable() {
			 public void run() {
				 new JAR3DMoleculeAlignerWindowed().setVisible(true);
			 }
		 });
	 }

	 public void loadAlignment() throws IOException
	 {
		 statusLabel.setText("Loading Alignment...");
		 int numMod = 0;
		 boolean modNum = false;
		 try{
			 numMod = Integer.parseInt(numSeqField.getText());
			 modNum = true;
		 }
		 catch (NumberFormatException e)
		 {
			 modNum = false;
		 }
		 
		 int range = 0;
		 boolean rangeNum = false;
		 try{
			 range = Integer.parseInt(limitField.getText());
			 rangeNum = true;
		 }
		 catch (NumberFormatException e)
		 {
			 rangeNum = false;
		 }
		 
		 if(((String)seqMenu.getSelectedItem() != null) && ((String)modelMenu.getSelectedItem() != null) && modNum && rangeNum)
		 {
			 Vector sequenceData = Alignment.loadFasta((String)seqMenu.getSelectedItem()); 

			 Vector parseData = Alignment.doParse(sequenceData,numMod,(String)modelMenu.getSelectedItem(), range);
	
			 alignment = Alignment.getAlignment(sequenceData);	
	
			 alignmentList = new JList(alignment);
			 alignmentList.setFont(new java.awt.Font("Lucida Console", 0, 11));
			 alignmentList.setModel(new javax.swing.AbstractListModel() {
				 public int getSize() { return alignment.size(); }
				 public Object getElementAt(int i) { return alignment.get(i); }
			 });
			 alignmentPane.setViewportView(alignmentList);
			 statusLabel.setText("Alignment Loaded");
			 statusIcon.setIcon(new javax.swing.JLabel() {
		            
					public javax.swing.Icon getIcon() {
		                try {
		                    return new javax.swing.ImageIcon(
		                        new java.net.URL("http://i7.tinypic.com/5y00but.gif")
		                    );
		                } catch (java.net.MalformedURLException e) {
		                }
		                return null;
		            }
		        }.getIcon());
		 }
		 else
		 {
			 statusLabel.setText("Please check input sources.");
			 statusIcon.setIcon(new javax.swing.JLabel() {
		            
					public javax.swing.Icon getIcon() {
		                try {
		                    return new javax.swing.ImageIcon(
		                        new java.net.URL("http://i10.tinypic.com/6f6q2d4.jpg")
		                    );
		                } catch (java.net.MalformedURLException e) {
		                }
		                return null;
		            }
		        }.getIcon());
		 }
	 }

	 public void getFiles()
	 {	
		 String filedir ;
		 String curDir = System.getProperty("user.dir");
		 sequences = new Vector();
		 File f1 = new File ( curDir + "\\sequences" ) ;

		 // Get all the files and directory under your diretcory
		 File[] seqfiles = f1.listFiles();

		 for ( int i = 0 ; i < seqfiles.length ; i ++ ) {
			 if ( seqfiles[i].isFile() && seqfiles[i].getName().substring(seqfiles[i].getName().length()-5,seqfiles[i].getName().length()).equals("fasta"))
			 {
				 sequences.add(seqfiles[i].getName());
			 }
		 }

		 models = new Vector();
		 File f2 = new File ( curDir +"\\models" ) ;

		 // Get all the files and directory under your diretcory
		 File[] modfiles= f2.listFiles();

		 for ( int i = 0 ; i < modfiles.length ; i ++ ) {
			 if ( modfiles[i].isFile() && modfiles[i].getName().substring(modfiles[i].getName().length()-3,modfiles[i].getName().length()).equals("txt"))
			 {
				 models.add(modfiles[i].getName());
			 }
		 }    	
	 }

	 // Variables declaration - do not modify                     
	 private javax.swing.JButton alignButton;
	    private javax.swing.JList alignmentList;
	    private javax.swing.JScrollPane alignmentPane;
	    private javax.swing.JPanel alignmentPanel;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JProgressBar jProgressBar1;
	    private javax.swing.JTextField limitField;
	    private javax.swing.JPanel limitPanel;
	    private javax.swing.JComboBox modelMenu;
	    private javax.swing.JPanel modelPanel;
	    private javax.swing.JTextField numSeqField;
	    private javax.swing.JPanel numSeqPanel;
	    private javax.swing.JComboBox seqMenu;
	    private javax.swing.JPanel seqPanel;
	    private javax.swing.JLabel statusIcon;
	    private javax.swing.JTextField statusLabel;
	 // End of variables declaration                   

}