package edu.bgsu.rna.jar3d.query;

public class QueryLoadingFailed extends Exception {

	/**
	 * Autogenerated.
	 */
	private static final long serialVersionUID = -4978273342511085294L;

	public QueryLoadingFailed(String err) {
		super(err);
	}
}
